export const GET_DEAN_SCHOOL_YEAR = 'GET_DEAN_SCHOOL_YEAR';
export const GET_DEAN_SCHOOL_YEAR_SUCCESS = 'GET_DEAN_SCHOOL_YEAR_SUCCESS';
export const GET_DEAN_SCHOOL_YEAR_FAIL = 'GET_DEAN_SCHOOL_YEAR_FAIL';