export const GET_LECTURER_SCHOOL_YEAR = 'GET_LECTURER_SCHOOL_YEAR';
export const GET_LECTURER_SCHOOL_YEAR_SUCCESS = 'GET_LECTURER_SCHOOL_YEAR_SUCCESS';
export const GET_LECTURER_SCHOOL_YEAR_FAIL = 'GET_LECTURER_SCHOOL_YEAR_FAIL';