export const GET_LECTURER_STUDENT_CLASS = 'GET_LECTURER_STUDENT_CLASS';
export const GET_LECTURER_STUDENT_CLASS_SUCCESS = 'GET_LECTURER_STUDENT_CLASS_SUCCESS';
export const GET_LECTURER_STUDENT_CLASS_FAIL = 'GET_LECTURER_STUDENT_CLASS_FAIL';