export const GET_LECTURE_DETAIL_COURSE = 'GET_LECTURE_DETAIL_COURSE';
export const GET_LECTURE_DETAIL_COURSE_SUCCESS = 'GET_LECTURE_DETAIL_COURSE_SUCCESS';
export const GET_LECTURE_DETAIL_COURSE_FAIL = 'GET_LECTURE_DETAIL_COURSE_FAIL';
                    