export const GET_LECTURER_CLASS_GRADE = 'GET_LECTURER_CLASS_GRADE';
export const GET_LECTURER_CLASS_GRADE_SUCCESS = 'GET_LECTURER_CLASS_GRADE_SUCCESS';
export const GET_LECTURER_CLASS_GRADE_FAIL = 'GET_LECTURER_CLASS_GRADE_FAIL';