export const GET_STUDENT_SCHOOL_YEAR = 'GET_STUDENT_SCHOOL_YEAR';
export const GET_STUDENT_SCHOOL_YEAR_SUCCESS = 'GET_STUDENT_SCHOOL_YEAR_SUCCESS';
export const GET_STUDENT_SCHOOL_YEAR_FAIL = 'GET_STUDENT_SCHOOL_YEAR_FAIL';