export const STUDENT_GET_ALL_GRADE = 'STUDENT_GET_ALL_GRADE';
export const STUDENT_GET_ALL_GRADE_SUCCESS = 'STUDENT_GET_ALL_GRADE_SUCCESS';
export const STUDENT_GET_ALL_GRADE_FAIL = 'STUDENT_GET_ALL_GRADE_FAIL';