export const GET_STUDENT_DETAIL_GRADE = 'GET_STUDENT_DETAIL_GRADE';
export const GET_STUDENT_DETAIL_GRADE_SUCCESS = 'GET_STUDENT_DETAIL_GRADE_SUCCESS';
export const GET_STUDENT_DETAIL_GRADE_FAIL = 'GET_STUDENT_DETAIL_GRADE_FAIL';