export const PDT_SCHOOL_YEAR = 'PDT_SCHOOL_YEAR';
export const PDT_SCHOOL_YEAR_SUCCESS = 'PDT_SCHOOL_YEAR_SUCCESS';
export const PDT_SCHOOL_YEAR_FAIL = 'PDT_SCHOOL_YEAR_FAIL';

export const PDT_DEPARTMENT = 'PDT_DEPARTMENT';
export const PDT_DEPARTMENT_SUCCESS = 'PDT_DEPARTMENT_SUCCESS';
export const PDT_DEPARTMENT_FAIL = 'PDT_DEPARTMENT_FAIL';

export const PDT_COURSE = 'PDT_COURSE';
export const PDT_COURSE_SUCCESS = 'PDT_COURSE_SUCCESS';
export const PDT_COURSE_FAIL = 'PDT_COURSE_FAIL';

export const PDT_STUDENT_CLASS = 'PDT_STUDENT_CLASS';
export const PDT_STUDENT_CLASS_SUCCESS = 'PDT_STUDENT_CLASS_SUCCESS';
export const PDT_STUDENT_CLASS_FAIL = 'PDT_STUDENT_CLASS_FAIL';

export const PDT_OUTLINE = 'PDT_OUTLINE';
export const PDT_OUTLINE_SUCCESS = 'PDT_OUTLINE_SUCCESS';
export const PDT_OUTLINE_FAIL = 'PDT_OUTLINE_FAIL';

export const PDT_SUBMIT_GRADE = 'PDT_SUBMIT_GRADE';
export const PDT_SUBMIT_GRADE_SUCCESS = 'PDT_SUBMIT_GRADE_SUCCESS';
export const PDT_SUBMIT_GRADE_FAIL = 'PDT_SUBMIT_GRADE_FAIL';

export const PDT_HANDLE_SHOW = 'PDT_HANDLE_SHOW'