export const GET_ANNOUNCE = 'GET_ANNOUNCE'; // pdt
export const GET_ANNOUNCE_SUCCESS = 'GET_ANNOUNCE_SUCCESS';
export const GET_ANNOUNCE_FAIL = 'GET_ANNOUNCE_FAIL';

export const GET_ANNOUNCE_FOR_DEAN = 'GET_ANNOUNCE_FOR_DEAN';
export const GET_ANNOUNCE_FOR_DEAN_SUCCESS = 'GET_ANNOUNCE_FOR_DEAN_SUCCESS';
export const GET_ANNOUNCE_FOR_DEAN_FAIL = 'GET_ANNOUNCE_FOR_DEAN_FAIL';

export const GET_ANNOUNCE_FOR_LECTURER = 'GET_ANNOUNCE_FOR_LECTURER';
export const GET_ANNOUNCE_FOR_LECTURER_SUCCESS = 'GET_ANNOUNCE_FOR_LECTURER_SUCCESS';
export const GET_ANNOUNCE_FOR_LECTURER_FAIL = 'GET_ANNOUNCE_FOR_LECTURER_FAIL';


export const GET_ANNOUNCE_FOR_STUDENT = 'GET_ANNOUNCE_FOR_STUDENT';
export const GET_ANNOUNCE_FOR_STUDENT_SUCCESS = 'GET_ANNOUNCE_FOR_STUDENT_SUCCESS';
export const GET_ANNOUNCE_FOR_STUDENT_FAIL = 'GET_ANNOUNCE_FOR_STUDENT_FAIL';

