export const PDT_TRANSCRIPT_HANDLE_SHOW = 'PDT_TRANSCRIPT_HANDLE_SHOW';

export const PDT_ALL_COURSE = 'PDT_ALL_COURSE';
export const PDT_ALL_COURSE_SUCCESS = 'PDT_ALL_COURSE_SUCCESS';
export const PDT_ALL_COURSE_FAIL = 'PDT_ALL_COURSE_FAIL';

export const PDT_ALL_DEPARTMENT = 'PDT_ALL_DEPARTMENT';
export const PDT_ALL_DEPARTMENT_SUCCESS = 'PDT_ALL_DEPARTMENT_SUCCESS';
export const PDT_ALL_DEPARTMENT_FAIL = 'PDT_ALL_DEPARTMENT_FAIL';

export const PDT_ALL_CLASS = 'PDT_ALL_CLASS';
export const PDT_ALL_CLASS_SUCCESS = 'PDT_ALL_CLASS_SUCCESS';
export const PDT_ALL_CLASS_FAIL = 'PDT_ALL_CLASS_FAIL';

export const PDT_ALL_STUDENT_CLASS = 'PDT_ALL_STUDENT_CLASS';
export const PDT_ALL_STUDENT_CLASS_SUCCESS = 'PDT_ALL_STUDENT_CLASS_SUCCESS';
export const PDT_ALL_STUDENT_CLASS_FAIL = 'PDT_ALL_STUDENT_CLASS_FAIL';

export const PDT_OUTLINE = 'PDT_OUTLINE';
export const PDT_OUTLINE_SUCCESS = 'PDT_OUTLINE_SUCCESS';
export const PDT_OUTLINE_FAIL = 'PDT_OUTLINE_FAIL';

export const PDT_SUBMIT_GRADE = 'PDT_SUBMIT_GRADE';
export const PDT_SUBMIT_GRADE_SUCCESS = 'PDT_SUBMIT_GRADE_SUCCESS';
export const PDT_SUBMIT_GRADE_FAIL = 'PDT_SUBMIT_GRADE_FAIL';

export const PDT_HANDLE_SHOW = 'PDT_HANDLE_SHOW'