export const GET_BALANCE = 'GET_BALANCE';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAIL = 'GET_BALANCE_FAIL';
export const UPDATE_BALANCE_FOR_ADMIN = 'UPDATE_BALANCE_FOR_ADMIN';

