export const GET_DEPARTMENT_FOR_ADMIN = 'GET_DEPARTMENT_FOR_ADMIN';
export const GET_DEPARTMENT_FOR_ADMIN_SUCCESS = 'GET_DEPARTMENT_FOR_ADMIN_SUCCESS';
export const GET_DEPARTMENT_FOR_ADMIN_FAIL = 'GET_DEPARTMENT_FOR_ADMIN_FAIL';