export const GET_WALLET_ADDRESS = 'GET_WALLET_ADDRESS';
export const GET_WALLET_ADDRESS_SUCCESS = 'GET_WALLET_ADDRESS_SUCCESS';
export const GET_WALLET_ADDRESS_FAIL = 'GET_WALLET_ADDRESS_FAIL';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
