export const GET_REQUEST_FOR_PDT = 'GET_REQUEST_FOR_PDT'; // pdt
export const GET_REQUEST_FOR_PDT_SUCCESS = 'GET_REQUEST_FOR_PDT_SUCCESS';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const GET_REQUEST_FOR_PDT_FAIL = 'GET_REQUEST_FOR_PDT_FAIL';

export const GET_REQUEST_FOR_DEAN = 'GET_REQUEST_FOR_DEAN'; // pdt
export const GET_REQUEST_FOR_DEAN_SUCCESS = 'GET_REQUEST_FOR_DEAN_SUCCESS';
export const GET_REQUEST_FOR_DEAN_FAIL = 'GET_REQUEST_FOR_DEAN_FAIL';


export const GET_REQUEST_FOR_LECTURER = 'GET_REQUEST_FOR_LECTURER'; // pdt
export const GET_REQUEST_FOR_LECTURER_SUCCESS = 'GET_REQUEST_FOR_LECTURER_SUCCESS';
export const GET_REQUEST_FOR_LECTURER_FAIL = 'GET_REQUEST_FOR_LECTURER_FAIL';


