
export const LECTURER_REQUEST_UPLOAD_GRADE = 'LECTURER_REQUEST_UPLOAD_GRADE'; // pdt
export const LECTURER_REQUEST_UPLOAD_GRADE_SUCCESS = 'LECTURER_REQUEST_UPLOAD_GRADE_SUCCESS';
export const LECTURER_REQUEST_UPLOAD_GRADE_FAIL = 'LECTURER_REQUEST_UPLOAD_GRADE_FAIL';
