export const UPDATE_REQUEST_DB_FOR_PDT = 'UPDATE_REQUEST_DB_FOR_PDT'; // pdt
export const UPDATE_REQUEST_DB_FOR_PDT_SUCCESS = 'UPDATE_REQUEST_DB_FOR_PDT_SUCCESS';
export const UPDATE_REQUEST_DB_FOR_PDT_FAIL = 'UPDATE_REQUEST_DB_FOR_PDT_FAIL';


export const UPDATE_REQUEST_DB_FOR_DEAN = 'UPDATE_REQUEST_DB_FOR_DEAN'; // pdt
export const UPDATE_REQUEST_DB_FOR_DEAN_SUCCESS = 'UPDATE_REQUEST_DB_FOR_DEAN_SUCCESS';
export const UPDATE_REQUEST_DB_FOR_DEAN_FAIL = 'UPDATE_REQUEST_DB_FOR_DEAN_FAIL';

export const UPDATE_REQUEST_DB_FOR_LECTURER = 'UPDATE_REQUEST_DB_FOR_LECTURER'; // pdt
export const UPDATE_REQUEST_DB_FOR_LECTURER_SUCCESS = 'UPDATE_REQUEST_DB_FOR_LECTURER_SUCCESS';
export const UPDATE_REQUEST_DB_FOR_LECTURER_FAIL = 'UPDATE_REQUEST_DB_FOR_LECTURER_FAIL';