export const GET_DEAN_KHOA = 'GET_DEAN_KHOA';
export const GET_DEAN_KHOA_SUCCESS = 'GET_DEAN_KHOA_SUCCESS';
export const GET_DEAN_KHOA_FAIL = 'GET_DEAN_KHOA_FAIL';

export const GET_DEAN_CLASS = 'GET_DEAN_CLASS';
export const GET_DEAN_CLASS_SUCCESS = 'GET_DEAN_CLASS_SUCCESS';
export const GET_DEAN_CLASS_FAIL = 'GET_DEAN_CLASS_FAIL';

export const GET_DEAN_STUDENT_CLASS = 'GET_DEAN_STUDENT_CLASS';
export const GET_DEAN_STUDENT_CLASS_SUCCESS = 'GET_DEAN_STUDENT_CLASS_SUCCESS';
export const GET_DEAN_STUDENT_CLASS_FAIL = 'GET_DEAN_STUDENT_CLASS_FAIL';

export const GET_DEAN_STUDENT_COURSE = 'GET_DEAN_STUDENT_COURSE';
export const GET_DEAN_STUDENT_COURSE_SUCCESS = 'GET_DEAN_STUDENT_COURSE_SUCCESS';
export const GET_DEAN_STUDENT_COURSE_FAIL = 'GET_DEAN_STUDENT_COURSE_FAIL';


export const DEAN_HANDLE_SHOW = 'DEAN_HANDLE_SHOW';